name: Go CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - name: Check out calculator codes
        uses: actions/checkout@v2
      - name: Setup go using Go version 1.13.7
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.7'
      - name: Run version check
        run: go version
      - name: Install Dependencies
        id: InstallDeps
        run: |
          go get github.com/tebeka/go2xunit
      - if: ${{success()}}
        run: |
          go get github.com/franela/goblin
      - if: ${{success()}}
        name: Test using Go Goblin
        run: |
          go test -v
          go test -v | go2xunit > report.xml    
      - if: ${{failure()}}
        name: Create Issues
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}
      - name: Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: report.xml
